/*
************************************************************************
ÅyFile NameÅzÉäÉZÉbÉgäÑÇËçûÇ›èàóù
ÅyDescriptionÅz
ÅyRevision HistoryÅz
   REV.00 2013-11-04  BY T.OOSAKI
   REV.XX 20XX-XX-XX  BY X.XXXXXX
   REV.XX 20XX-XX-XX  BY X.XXXXXX
   REV.XX 20XX-XX-XX  BY X.XXXXXX

                      (C) 2013 IPL CORPORATION All Rights Reserved
************************************************************************
*/

/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Mon, Jun 11, 2007                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :H8/36064                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/

#include	"HALIn.h"
#include	"stacksct.h"
#include	<machine.h>
#include	<_h_c_lib.h>

#if ( HAL_HW_SWITCH == HAL_HW_H836064S )

extern void main(void);
__entry(vect=0) void PowerON_Reset(void);

#pragma section ResetPRG
__entry(vect=0) void PowerON_Reset(void)
{ 
	 set_imask_ccr((UB)1);
	_INITSCT();
	set_imask_ccr((UB)0);

	main();
	sleep();
	while(1);
}
#endif
