#ifndef _STACKSCT_H_
#define _STACKSCT_H_

/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Mon, Jun 11, 2007                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :H8/36064                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/

#if ( HAL_HW_SWITCH == HAL_HW_H836064S )
#pragma stacksize 0x100         /* Do not modify this line. */
#endif

#endif /* _STACKSCT_H_ */
