/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Mon, Jun 11, 2007                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :H8/36064                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
                  

#include	<machine.h>
#include	<_h_c_lib.h>
#include 	"vs-wrc003lv.h"
#include	"stacksct.h"

extern void main(void);
__entry(vect=0) void PowerON_Reset(void);
//__interrupt(vect=1) void Manual_Reset(void);

//#ifdef __cplusplus				// Remove the comment when you use SIM I/O
//extern "C" {
//#endif
//extern void _INIT_IOLIB(void);
//extern void _CLOSEALL(void);
//#ifdef __cplusplus
//}
//#endif

//extern void srand(_UINT);		// Remove the comment when you use rand()
//extern _SBYTE *_s1ptr;				// Remove the comment when you use strtok()
		
//#ifdef __cplusplus				// Remove the comment when you use Hardware Setup
//extern "C" {
//#endif
//extern void HardwareSetup(void);
//#ifdef __cplusplus
//}
//#endif

//#ifdef __cplusplus			// Remove the comment when you use global class object
//extern "C" {					// Sections C$INIT and C$END will be generated
//#endif
//extern void _CALL_INIT(void);
//extern void _CALL_END(void);
//#ifdef __cplusplus
//}
//#endif

	
#pragma section ResetPRG

__entry(vect=0) void PowerON_Reset(void)
{ 
	 set_imask_ccr((UBYTE)1);
	_INITSCT();

//	_CALL_INIT();					// Remove the comment when you use global class object

//	_INIT_IOLIB();					// Remove the comment when you use SIM I/O

//	errno=0;						// Remove the comment when you use errno
//	srand((_UINT)1);					// Remove the comment when you use rand()
//	_s1ptr=NULL;					// Remove the comment when you use strtok()
		
//	HardwareSetup();				// Remove the comment when you use Hardware Setup
	set_imask_ccr((UBYTE)0);

	main();

//	_CLOSEALL();					// Remove the comment when you use SIM I/O

//	_CALL_END();					// Remove the comment when you use global class object
	
	sleep();	
	while(1);
}


//__interrupt(vect=1) void Manual_Reset(void)	// Remove the comment when you use Manual Reset
//{
//} 
